from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime
from typing import Literal, Optional

AdvisoryStatus = Literal["verified", "partial", "unverified", "unavailable"]
GeneratedBy = Literal["l5_q1_agent", "human", "none"]
CitationStatus = Literal["all_verified", "some_failed_retry_ok", "some_failed_no_retry", "not_attempted"]

@dataclass(frozen=True)
class AdvisoryDerivation:
    field_id: str
    generated_by: GeneratedBy
    display_status: AdvisoryStatus
    body: Optional[str]
    method_id: str
    evidence_ids: list[str]
    citation_status: CitationStatus
    fallback_used: bool
    computed_at: datetime
    as_of: datetime
    unavailable_reason: Optional[str] = None

    def is_present(self) -> bool:
        return self.body is not None

def validate_advisory(a: AdvisoryDerivation) -> None:
    if a.computed_at < a.as_of:
        raise ValueError("computed_at must be >= as_of")
    if a.display_status == "unavailable":
        if a.body is not None:
            raise ValueError("unavailable advisory must have body=None")
        if not a.unavailable_reason:
            raise ValueError("unavailable advisory must have unavailable_reason")
    if a.display_status == "verified":
        if not a.evidence_ids:
            raise ValueError("verified advisory must list at least one evidence_id")
        if a.fallback_used:
            raise ValueError("verified advisory cannot have fallback_used=True")
        if a.generated_by != "l5_q1_agent":
            raise ValueError("verified advisory must be generated by l5_q1_agent")
        if a.citation_status != "all_verified":
            raise ValueError("verified advisory requires all_verified citation status")
    if a.display_status == "partial":
        if a.citation_status not in ("some_failed_retry_ok", "some_failed_no_retry"):
            raise ValueError("partial advisory requires failed citation status")
    if a.fallback_used and a.display_status == "verified":
        raise ValueError("fallback_used=True cannot be verified")
